# Generated by Django 4.0.2 on 2022-02-27 15:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('contact_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rue / Numéro')),
                ('address_zipcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('address_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='STRIPE PaymentIntent ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif?')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=shop.models.generate_invoice_number, max_length=255, unique=True, verbose_name='Numéro')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facturation')),
                ('invoice_status', models.CharField(choices=[('waiting', 'En cours'), ('done', 'Payée')], default='waiting', max_length=25, verbose_name='Statut')),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('contact_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rue / Numéro')),
                ('address_zipcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('address_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='STRIPE PaymentIntent ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('vat', models.PositiveIntegerField(default=21, verbose_name='TVA (%)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix (HTVA)')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('product_vat', models.PositiveIntegerField(default=21, verbose_name='TVA (%)')),
                ('product_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix (HTVA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Facture (Produit)',
                'verbose_name_plural': 'Facture (Produits)',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('product_vat', models.PositiveIntegerField(default=21, verbose_name='TVA (%)')),
                ('product_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix (HTVA)')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Panier')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Panier (Produit)',
                'verbose_name_plural': 'Panier (Produits)',
            },
        ),
    ]
